### ISSUE TITLE
Vector / chunked / batch mode

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#312]
This one is rather easy in principle: just wrap the JVP/VJP/HVP seed in a Batch struct that is essentially a named tuple, and dispatch on that

**Comment by gdalle** [comment]
Partially solved by #320, still needs:

- [x] Batched HVPs based on batched pushforward/pullback (done in #330 except for reverse-over-forward)
- [x] Batched pushforward with ForwardDiff (done in #328)
- [ ] Batched pushforward and pullback with Enzyme
- [ ] Tests on efficiency (type stability, allocations)
- [x] Independent tests of the primitive operators with batched scenarios (done in #331)

**Comment by gdalle** [comment]
It would be nice to avoid the distinction between `operator` and `operator_batched`, but that would require wrapping inputs into a `Single` struct or so

**Comment by gdalle** [comment]
Further improved by #412, which makes batch mode the default that extensions need to implement

**Comment by gdalle** [comment]
Batch mode for Enzyme is nearly complete since #471, it only needs https://github.com/EnzymeAD/Enzyme.jl/issues/1883 to work with out-of-place functions
